apiVersion: v1
kind: Namespace
metadata:
  name: config1
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: config1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: config1
---

kind: Pod
apiVersion: v1
metadata:
  name: pod1
  namespace: config1
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc1
  containers:
    - name: debugger
      image: busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume

