apiVersion: v1
kind: Namespace
metadata:
  name: config6
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc6
  namespace: config6
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: config4
---

kind: Pod
apiVersion: v1
metadata:
  name: pod6
  namespace: config6
spec:
  volumes:
    - name: volume
      persistentVolumeClaim:
       claimName: pvc6
  containers:
    - name: debugger
      image: busybox:1.35.0
      imagePullPolicy: IfNotPresent
      command: ['sleep', '3600']
      volumeMounts:
        - mountPath: "/data"
          name: volume

