{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "backendName": "BackendForNAS-Qtree",
    "managementLIF": "192.168.0.135",
    "dataLIF": "192.168.0.132",
    "svm": "svm1",
    "username": "vsadmin",
    "password": "Netapp1!"
}
